<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <RootNamespace>DynaAppX</RootNamespace>
    <AssemblyName>DynaAppX</AssemblyName>
    <TargetFramework>net48</TargetFramework>
    <Version>1.0.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Authors></Authors>
    <Company></Company>
    <Copyright>Copyright © 2024</Copyright>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="XrmToolBoxPackage" Version="1.2022.5.56" />
  </ItemGroup>

  <PropertyGroup>
    <PostBuildEvent>
      IF NOT EXIST $(TargetDir)XrmToolBox mkdir $(TargetDir)XrmToolBox
      IF NOT EXIST $(TargetDir)XrmToolBox\Plugins mkdir $(TargetDir)XrmToolBox\Plugins
      move /Y "$(TargetDir)DynaAppX.dll" $(TargetDir)XrmToolBox\Plugins\
      IF "$(ConfigurationName)"=="Debug" (
        move /Y "$(TargetDir)DynaAppX.pdb" $(TargetDir)XrmToolBox\Plugins\
      )
    </PostBuildEvent>
  </PropertyGroup>
</Project>